#!/usr/bin/python3

import fhs
import websocketd
import userdata

fhs.option('game', 'game name', default = 'test')
fhs.option('prefix', 'db prefix', default = 'test')
fhs.option('port', 'port to listen on', default = '8878')
fhs.option('userdata', 'userdata server', default = '8879')
config = fhs.init(help = 'test game for userdata', version = '0.1', contact = 'Bas Wijnen <wijnen@debian.org>')

class Player:
	def __init__(self, remote, name, userdata):
		self._remote = remote
		self._name = name
		self._data = userdata
		self._remote.cheer.event()

userdata.run(config['port'], 'my-test-game', Player, config['userdata'], '')
