#!/usr/bin/python3

import fhs
import websocketd
import userdata

fhs.option('port', 'port to listen on', default = '8878')
fhs.option('userdata', 'userdata server', default = '8879')
fhs.option('username', 'userdata login name', default = 'own-all')
fhs.option('password', 'userdata password', default = 'own-all')
fhs.option('game', 'userdata game id', default = 'own-all')
config = fhs.init(help = 'test game for userdata', version = '0.1', contact = 'Bas Wijnen <wijnen@debian.org>')

class Player:
	def __init__(self, remote, name, data):
		self.remote = remote
		self.name = name
		self.data = data
	def set(self, num):
		self.data.update('nums', {'num': num}, condition = ())
	def get(self):
		return self.data.select('nums', 'num')[0][0]
	def get_name(self):
		return self.name

server = userdata.setup(Player, config, default = '', allow_other = False, httpdirs = ('own-all-html',))

if len(server._userdata_servers[''][0].select(0, 'nums', 'num')) == 0:
	server._userdata_servers[''][0].insert(0, 'nums', {'num': 0})

websocketd.fgloop()
