#!/usr/bin/python3

import fhs
import websocketd
import userdata

fhs.option('port', 'port to listen on', default = '8878')
config = userdata.fhs_init('http://localhost:8879', 'remote-only', help = 'test game for userdata', version = '0.1', contact = 'Bas Wijnen <wijnen@debian.org>')

if config['game-url'] == '':
	config['game-url'] = 'http://localhost:%s' % config['port']

class Player:
	def __init__(self, uid, data):
		self.uid = uid
		self.data = data
		print('player logging in')
	def set(self, num):
		self.data.update('nums', {'num': num}, condition = ())
	def get(self):
		return self.data.select('nums', 'num')[0][0]
	def get_name(self):
		return self.name

db_config = {'logins': [('num', 'INT'), ('msg', 'VARCHAR(255)')]}
player_config = {'stats': [('hp', 'INT'), ('mana', 'INT')]}

server, local = userdata.setup(Player, config, db_config, player_config, allow_local = False, allow_other = True, httpdirs = ('remote-only-html',))

if len(local.select(0, 'logins', 'num')) == 0:
	local.insert(0, 'logins', {'num': 0})

print('server is running on port', config['port'])

websocketd.fgloop()
